In [5]:
import numpy as np

In [7]:
X = np.random.randint(5,size=(6, 100))
Y = np.array([1,2,3,4,5,6])

In [8]:
X

array([[1, 0, 1, 4, 2, 3, 0, 3, 1, 0, 3, 4, 0, 4, 2, 2, 2, 3, 1, 2, 4, 3,
        0, 2, 1, 0, 0, 0, 0, 1, 2, 4, 0, 3, 4, 2, 3, 3, 1, 4, 1, 4, 3, 1,
        2, 4, 3, 1, 4, 2, 2, 1, 0, 0, 3, 2, 4, 3, 3, 4, 3, 1, 1, 0, 2, 3,
        2, 0, 3, 0, 3, 3, 4, 0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 4, 4, 1, 1, 2,
        2, 4, 1, 0, 4, 4, 2, 3, 3, 0, 2, 0],
       [3, 3, 3, 4, 2, 1, 0, 1, 2, 2, 2, 3, 3, 4, 0, 3, 2, 1, 3, 2, 4, 3,
        3, 0, 4, 4, 2, 4, 0, 4, 2, 3, 1, 3, 3, 3, 1, 4, 3, 1, 0, 2, 1, 0,
        1, 0, 1, 2, 2, 2, 2, 1, 0, 2, 4, 1, 1, 0, 2, 3, 2, 0, 3, 3, 0, 1,
        2, 3, 1, 0, 4, 2, 2, 3, 4, 1, 0, 3, 0, 2, 0, 0, 2, 4, 1, 3, 2, 1,
        1, 4, 2, 3, 0, 2, 2, 1, 0, 1, 1, 2],
       [4, 3, 1, 2, 1, 1, 1, 3, 2, 3, 3, 2, 0, 3, 4, 4, 3, 1, 3, 2, 3, 3,
        4, 1, 2, 0, 0, 4, 2, 3, 1, 3, 3, 1, 0, 1, 2, 2, 2, 4, 0, 0, 0, 0,
        4, 2, 1, 1, 2, 3, 3, 4, 1, 1, 0, 4, 2, 0, 4, 0, 0, 1, 0, 4, 3, 4,
        0, 2, 1, 0, 0, 2, 2, 3, 4, 2, 1, 1, 3, 4, 3, 4, 2, 2, 0, 3, 1, 0,
        2, 0, 4, 2, 4,

In [9]:
Y

array([1, 2, 3, 4, 5, 6])

In [13]:
# 나이브 베이즈 모델 만들고 위의 데이터를 훈련데이터로 훈련
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()

In [14]:
clf.fit(X,Y)

MultinomialNB()

In [15]:
# 4번째 데이터의 class예측
print(clf.predict(X[3].reshape(1,100)))

[4]


In [16]:
# 전체 훈련데이터 예측
clf.predict(X)

array([1, 2, 3, 4, 5, 6])