In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]]) # ndarray데이터 타입으로 변환

print(type(arr1))
print(arr1.dtype)
print(arr1.shape) # array 차원/크기 > 튜플 형태로 표현

<class 'numpy.ndarray'>
int64
(2, 3)


In [4]:
arr_seq = np.arange(20)
print(arr_seq)
print(arr1.dtype)
print(arr1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64
(2, 3)


In [5]:
# 인덱싱: 넘파이에서 일부 데이터 세트나 특정 데이터만 선택
arr_1 = np.arange(start=1, stop=20)
print(arr_1)

val = arr_1[3]
print(arr_1[3], arr_1[-1])

arr_1[3] = 99
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4 19
[ 1  2  3 99  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
arr_2 = np.arange(start=1, stop=17)
arr_3 = arr_2.reshape(4,4)
print(arr_2)
print(arr_3)
print(arr_3[0,0], arr_3[2,1])

# 슬라이싱
print(arr_3[:3])
print(arr_3[3:])
print(arr_3[:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1 10
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [9]:
arr_4 = np.arange(start=1, stop=10)
print(arr_4)
arr_5 = arr_4[arr_4 > 5]
print(arr_5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [10]:
arr_4 > 5

array([False, False, False, False, False,  True,  True,  True,  True])